# Site settings
title: 'Remotework.jp'
description: 'Tech remote jobs in Japan in Japanese and English.'
baseurl: '/'
url: 'https://remotework.jp'

# Build settings
markdown: kramdown
# permalink: /:title/     #permalinks are set per file to handle multilanguages

plugins:
  - jekyll-paginate

paginate: 10

# Plugins
plugins_dir:
  - jekyll-include-cache

exclude:
  - .jekyll-cache
