# Site settings
title: 'Remotework.jp'
email: hatem.houssein@gmail.com
description: 'Simple and responsive website for remote work in Japan in Japanese and English.'
baseurl: ''
url: 'https://remotework.jp/'
twitter_username: 'hatem_hou'
github_username: 'SaulSilver'
color_theme: '#3c0909'
color_text: '#fff'

# Build settings
markdown: kramdown
# permalink: /:title/     #permalinks are set per file to handlem multilanguages

plugins:
  - jekyll-paginate

paginate: 10

# Plugins
plugins_dir:
  - jekyll-admin
